server:
  port: 8790
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8771/eureka/
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/** #以/api-a/ 开头的请求都转发给service-ribbon服务
      serviceId: service-ribbon
    api-b:
      path: /api-b/** #以/api-b/开头的请求都转发给service-feign服务；
      serviceId: service-feign